spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  datasource:
    url: jdbc:mysql://192.168.16.219:33306/iam_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    database: 4
    lettuce:
      shutdown-timeout: 200ms
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 2
        max-wait: -1ms
  cache:
    multi:
      l1:
        enabled: true # 是否开启一级缓存
        type: caffeine # 一级缓存实现。目前支持caffeine和guava
      l2:
        enabled: false # 是否开启二级缓存
        type: redis # 二级缓存的实现
      caches:
        permission: # 请求对应的权限缓存
          l1-spec: initialCapacity=50,maximumSize=500,expireAfterWrite=600s
          l2-spec: expiration=600
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
    metadata-map:
      VERSION: v1
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
    registryFetchIntervalSeconds: 10
    disable-delta: true
zuul:
  addHostHeader: true
  routes:
    iam:
      path: /iam/**
      serviceId: iam-service
    oauth:
      path: /oauth/**
      serviceId: oauth-server
      stripPrefix: false
      sensitiveHeaders: none
    notify:
      path: /notify/**
      serviceId: notify-service
    asgard:
      path: /asgard/**
      serviceId: asgard-service
    manager:
      path: /manager/**
      serviceId: manager-service
    file:
      path: /file/**
      serviceId: file-service
    org:
      path: /org/**
      serviceId: organization-service
    devops:
      path: /devops/**
      serviceId: devops-service
    agile:
      path: /agile/**
      serviceId: agile-service
    state:
      path: /state/**
      serviceId: state-machine-service
    issue:
      path: /issue/**
      serviceId: issue-service
    test-manager:
      path: /test/**
      serviceId: test-manager-service
    wiki:
      path: /wiki/**
      serviceId: wiki-service
    apim:
      path: /apim/**
      serviceId: apim-service
    foundation:
      path: /foundation/**
      serviceId: foundation-service
  semaphore:
    max-semaphores: 300
  sensitiveHeaders: Cookie,Set-Cookie
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 80000
choerodon:
  gateway:
    allowed:
      origin: '*'
    helper:
      service-id: gateway-helper
      enabled: true
      enabled-jwt-log: false
      jwt-key: choerodon # jwt的密钥
      oauth-info-uri: http://oauth-server/oauth/api/user # oauth获取userDetail地址
      permission:
        enabled: true # 是否开启权限校验
        skip-paths: /**/skip/**, /oauth/**,/prometheus,/health,/env,/metrics,/favicon.ico # 跳过权限校验路径
        cache-seconds: 600 # 请求地址和对应的权限缓存时间
        cache-size: 3000  # 请求地址和对应的权限缓存大小
security:
  oauth2:
    client:
      grant-type: client_credentials
    resource:
      userInfoUri: http://oauth-server/oauth/api/user
mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
  httpclient:
    enabled: false
  okhttp:
    enabled: true
logging:
  level:
    com.netflix.discovery.DiscoveryClient: warn